services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:4000
    volumes:
      - ./:/app
  
  postgres:
    image: 'postgres:16.2-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog-app
    ports:
      - 5432:5432
    volumes:
      - ./sql/query.sql:/docker-entrypoint-initdb.d/create_tables.sql